[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.214", features = ["derive"]}
tokio = {version = "1.41.1", features = ["full"]}

core = {path = "../../../core"}
persistence = {path = "../persistence"}