[package]
name = "persistence"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.214", features = ["derive"]}
sqlx = {version = "0.8.2", features = ["postgres", "json"]}
once_cell = "1.20.2"

core = {path = "../../../core"}